version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ccmuser
      MYSQL_PASSWORD: ccmpass
      MYSQL_DATABASE: ccmbase
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -P 3306 -u ccmuser --password=ccmpass | grep 'mysqld is alive' || exit 1"
        ]
      interval: 3s
      timeout: 10s
      retries: 3
    networks:
      - shared

  webservice:
    image: localhost:5000/webservice:latest
    volumes:
      - webservice_data:/appli
    networks:
      - shared
    ports:
      - "9015:9015"
    environment:
      - APP_PORT=9015
    command:
      - /bin/bash
      - -c
      - |
        php /appli/createbase.php
        php /appli/server.php
    depends_on:
      mariadb:
        condition: service_healthy

  php-fpm:
    container_name: php-fpm
    image: php:fpm
    command: sh -c "docker-php-ext-install mysqli pdo pdo_mysql && docker-php-ext-enable pdo_mysql && php-fpm"
    volumes:
      - webservice_data:/var/www/html/
    networks:
      - shared
    ports:
      - "9000:9000"
    expose:
      - 9000

  nginx:
    image: nginx:latest
    volumes:
      - webservice_data:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf

    ports:
      - "82:80"
    depends_on:
      - webservice
    networks:
      - shared

volumes:
  mariadb_data:
  webservice_data:


networks:
  shared:
